package com.rajashekar.feeservice.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.rajashekar.feeservice.entity.Receipt;
import com.rajashekar.feeservice.repository.ReceiptRepository;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.RoundingMode;
import java.time.format.DateTimeFormatter;


@Service
public class ReceiptService {

    @Autowired
    private ReceiptRepository receiptRepository;

   
    public List<Receipt> getAllReceipts() {
        return receiptRepository.findAll();
    }

    public Receipt getReceiptById(Long receiptId) {
        return receiptRepository.findById(receiptId)
                .orElseThrow(() -> new RuntimeException("Receipt not found with id: " + receiptId));
    }

    public List<Receipt> getReceiptsByStudentId(Long studentId) {
        return receiptRepository.findByStudentId(studentId);
    }
    
    public byte[] generateReceiptPdf(Long receiptId) {
        Receipt receipt = getReceiptById(receiptId);

        try (PDDocument document = new PDDocument();
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {

            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            PDType1Font titleFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font labelFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font valueFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                float y = 780;
                float left = 60;
                float lineGap = 22;

                // Title
                contentStream.beginText();
                contentStream.setFont(titleFont, 18);
                contentStream.newLineAtOffset(left, y);
                contentStream.showText("Fee Payment Receipt");
                contentStream.endText();

                y -= 35;

                y = writeLine(contentStream, labelFont, valueFont, left, y, "Receipt ID", String.valueOf(receipt.getReceiptId()));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Date & Time",
                        receipt.getDateTime() == null ? "" :
                                receipt.getDateTime().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Student Name", safe(receipt.getStudentName()));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Student ID", String.valueOf(receipt.getStudentId()));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "School Name", safe(receipt.getSchoolName()));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Grade", safe(receipt.getGrade()));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Reference Number", safe(receipt.getReferenceNumber()));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Card Number", safe(receipt.getCardNumber()));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Card Type", safe(receipt.getCardType()));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Fee Description", safe(receipt.getFeeDescription()));
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Amount",
                        receipt.getAmount() == null ? "" : receipt.getAmount().setScale(2, RoundingMode.HALF_UP).toString());
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Total",
                        receipt.getTotal() == null ? "" : receipt.getTotal().setScale(2, RoundingMode.HALF_UP).toString());
                y = writeLine(contentStream, labelFont, valueFont, left, y, "Status", safe(receipt.getStatus()));

                y -= lineGap;

                contentStream.beginText();
                contentStream.setFont(valueFont, 10);
                contentStream.newLineAtOffset(left, y);
                contentStream.showText("Generated by fee-service");
                contentStream.endText();
            }

            document.save(outputStream);
            return outputStream.toByteArray();

        } catch (IOException e) {
            throw new RuntimeException("Failed to generate PDF receipt", e);
        }
    }

    private float writeLine(PDPageContentStream contentStream,
                            PDType1Font labelFont,
                            PDType1Font valueFont,
                            float left,
                            float y,
                            String label,
                            String value) throws IOException {

        contentStream.beginText();
        contentStream.setFont(labelFont, 12);
        contentStream.newLineAtOffset(left, y);
        contentStream.showText(label + ":");
        contentStream.endText();

        contentStream.beginText();
        contentStream.setFont(valueFont, 12);
        contentStream.newLineAtOffset(left + 140, y);
        contentStream.showText(value == null ? "" : value);
        contentStream.endText();

        return y - 22;
    }

    private String safe(String value) {
        return value == null ? "" : value;
    }
}